[package]
name = "forward_auth_plugin"
version = "0.1.0"
authors = ["Paul Adams <nihaopaul@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []

[dependencies]
log = "0.4.22"
serde = "1.0.214"
serde_derive = "1.0.214"
serde_json = "1.0.132"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
